version: '3'
services:
  mysql:
    image: mysql:8.0.18
    ports:
      - 33060:3306
    volumes:
      - mysql-db-data:/var/lib/mysql
      
    environment: 
      
      MYSQL_ROOT_PASSWORD: 'secure'
      MYSQL_DATABASE: 'demo'
    networks: [pystack]

   
networks:
  pystack:

  
volumes:
  mysql-db-data:
  
  




